// aggregates.ts
// Interfaces for aggregate data structures used in the application.
// These define the shape of data from Firestore "Aggregates" subcollection documents
// (generated by the aggregateAllSales Cloud Function) and the processed branch aggregate
// data returned by client-side hooks.

import { Timestamp } from "firebase/firestore"; // For client-side Firestore Timestamps (use firebase-admin/firestore for server-side if needed)

/**
 * Interface for a raw aggregate document from the Firestore "Aggregates" subcollection
 * under a "Branches" document. This represents the full structure of data stored in each
 * aggregate document, as generated by the aggregateAllSales Cloud Function.
 * 
 * The document is stored at: Branches/{branchId}/Aggregates/{aggregateId}
 * where aggregateId is in the format "YYYY-MM-DD".
 * 
 * Fields like aggregateDate are used for querying and sorting (e.g., orderBy("aggregateDate", "desc")).
 * Timestamps are Firestore Timestamp objects.
 */
export interface AggregateDocument {
  aggregateDate: Timestamp; 
  branchId: string; 
  totalTransactions: number;
  grandTotal: number; 
  coins_1: number; 
  coins_5: number; 
  coins_10: number;
  coins_20: number;
  earliest: Timestamp | null;
  latest: Timestamp | null; 
  totalCoins: number; 
  createdAt: Timestamp; 
  processedAt: Timestamp; 

}


export interface BranchAggregateData {
  totalRevenue: number;
  totalTransactions: number; 
  location: string; 
  coinBreakdown: {
    peso1: number; 
    peso5: number; 
    peso10: number; 
    peso20: number; 
  };
  
}


export interface AggregatesQueryResult {
  aggregates: AggregateDocument[]; 
  hasMore: boolean; 
  lastVisible?: AggregateDocument; 
}
export interface HistoricalAggregate extends BranchAggregateData {
  date: string; 
  totalCoins?: number; 
  
}
