import jsPDF from 'jspdf';
import type { HarvestResult } from '@/hooks/use-unit-harvest';

export function generateHarvestPDF(
  result: HarvestResult,
  unitAlias: string,
  branchLocation: string
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const totalPages: number = doc.internal.pages ? doc.internal.pages.length - 1 : 1;
  let yPosition = 20;
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 128, 0);
  doc.text('EARLY HARVEST SUMMARY REPORT', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  
  // Generation date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 20;
  
  // Unit Information Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('UNIT INFORMATION', 20, yPosition);
  
  yPosition += 10;
  doc.setFontSize(10);
  doc.text(`Unit Alias: ${unitAlias}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Branch Location: ${branchLocation}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Harvest Date: ${result.harvestDate.toLocaleDateString()}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Date Range: ${result.dateRange.start} to ${result.dateRange.end}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Days Harvested: ${result.documentsUpdated}`, 20, yPosition);
  
  yPosition += 15;
  
  // Financial Summary Section
  doc.setFontSize(14);
  doc.text('FINANCIAL SUMMARY', 20, yPosition);
  
  yPosition += 10;
  doc.setFontSize(16);
  doc.setTextColor(0, 128, 0);
  doc.text(`Total Harvested: P${result.totalHarvested.toFixed(2)}`, 20, yPosition);
  
  yPosition += 15;
  
  // Coin Breakdown Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('COIN BREAKDOWN', 20, yPosition);
  
  yPosition += 10;
  doc.setFontSize(10);
  
  // Coin breakdown in two columns
  const coinData = [
    { label: 'P1 Coins:', value: result.coins_1 },
    { label: 'P5 Coins:', value: result.coins_5 },
    { label: 'P10 Coins:', value: result.coins_10 },
    { label: 'P20 Coins:', value: result.coins_20 },
  ];
  
  coinData.forEach((coin, index) => {
    const xPosition = index % 2 === 0 ? 20 : 110;
    const rowY = yPosition + Math.floor(index / 2) * 7;
    doc.text(`${coin.label}`, xPosition, rowY);
    doc.text(`${coin.value}`, xPosition + 40, rowY);
  });
  
  yPosition += 20;
  
  // Sales Count
  doc.text(`Total Transactions: ${result.sales_count}`, 20, yPosition);
  
  yPosition += 15;
  
  // Harvested Dates Section
  if (result.harvestedDates.length > 0) {
    doc.setFontSize(14);
    doc.text('HARVESTED DATES', 20, yPosition);
    
    yPosition += 10;
    doc.setFontSize(8);
    
    // Check if we need a new page
    const datesPerPage = 20;
    let currentDateIndex = 0;
    
    while (currentDateIndex < result.harvestedDates.length) {
      if (yPosition > 250 && currentDateIndex > 0) {
        doc.addPage();
        yPosition = 20;
      }
      
      const endIndex = Math.min(currentDateIndex + datesPerPage, result.harvestedDates.length);
      const currentDates = result.harvestedDates.slice(currentDateIndex, endIndex);
      
      // Display dates in 3 columns
      const datesPerColumn = Math.ceil(currentDates.length / 3);
      
      for (let col = 0; col < 3; col++) {
        const colX = 20 + col * 60;
        const colDates = currentDates.slice(col * datesPerColumn, (col + 1) * datesPerColumn);
        
        colDates.forEach((date, index) => {
          doc.text(date, colX, yPosition + index * 4);
        });
      }
      
      yPosition += datesPerColumn * 4 + 10;
      currentDateIndex = endIndex;
    }
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Report generated by Harvest System - Page 1 of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  // Save the PDF
  const fileName = `harvest-summary-${unitAlias}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

// Alternative function with more compact layout
export function generateCompactHarvestPDF(
  result: HarvestResult,
  unitAlias: string,
  branchLocation: string
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header with green background
  doc.setFillColor(0, 128, 0);
  doc.rect(0, 0, pageWidth, 30, 'F');
  
  // Title
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('HARVEST SUMMARY', pageWidth / 2, 18, { align: 'center' });
  
  let yPosition = 45;
  
  // Key information in a table-like format
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  
  const infoData = [
    { label: 'Unit:', value: unitAlias },
    { label: 'Branch:', value: branchLocation },
    { label: 'Harvest Date:', value: result.harvestDate.toLocaleDateString() },
    { label: 'Date Range:', value: `${result.dateRange.start} to ${result.dateRange.end}` },
    { label: 'Days Harvested:', value: result.documentsUpdated.toString() },
  ];
  
  infoData.forEach((item, index) => {
    doc.setTextColor(100, 100, 100);
    doc.text(item.label, 20, yPosition + index * 6);
    doc.setTextColor(0, 0, 0);
    doc.text(item.value, 60, yPosition + index * 6);
  });
  
  yPosition += 35;
  
  // Total amount highlighted
  doc.setFontSize(16);
  doc.setTextColor(0, 128, 0);
  doc.text(`TOTAL AMOUNT: P${result.totalHarvested.toFixed(2)}`, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 20;
  
  // Coin breakdown in a clean table
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('COIN BREAKDOWN', 20, yPosition);
  
  yPosition += 10;
  doc.setFontSize(10);
  
  const coins = [
    { denomination: 'P1', count: result.coins_1 },
    { denomination: 'P5', count: result.coins_5 },
    { denomination: 'P10', count: result.coins_10 },
    { denomination: 'P20', count: result.coins_20 },
  ];
  
  coins.forEach((coin, index) => {
    const rowY = yPosition + index * 7;
    doc.text(coin.denomination, 30, rowY);
    doc.text(coin.count.toString(), 80, rowY);
    doc.text(`P${(parseInt(coin.denomination.replace('P', '')) * coin.count).toFixed(2)}`, 120, rowY);
  });
  
  yPosition += 35;
  
  // Summary
  doc.text(`Total Transactions: ${result.sales_count}`, 20, yPosition);
  
  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  // Save
  const fileName = `harvest-${unitAlias}-${result.harvestDate.toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}